export type TaskStatus = "todo" | "in-progress" | "done";
export type TaskOwner = "Sahil" | "Saloni" | "Both" | "Unassigned";
export type TaskCategory =
  | "General Prep"
  | "Haldi"
  | "Mehendi"
  | "Ganesh Pooja + Wedding"
  | "Dinner / Hang"
  | "Night";

export interface Task {
  id: string;
  title: string;
  description: string;
  category: TaskCategory;
  dueDate: string;
  status: TaskStatus;
  owner: TaskOwner;
  fileIds: string[];
  contextLog: string[];
  decoratorTopic: boolean;
}

export interface DriveFile {
  id: string;
  name: string;
  mimeType: string;
  modifiedTime: string;
  size: string;
  iconLink: string;
  webViewLink: string;
  thumbnailLink?: string;
}

export interface CalendarEvent {
  id: string;
  title: string;
  date: string;
  type: "deadline" | "appointment" | "milestone";
  taskId?: string;
}

// Wedding date constant
export const WEDDING_DATE = new Date("2026-04-26T00:00:00");
export const WEDDING_VENUE = "Old Mill Park Amphitheatre";

// ─── Real Tasks from Planning Sheet ──────────────────────────────────────────

export const mockTasks: Task[] = [
  // ── General Prep ───────────────────────────────────────────────────────────
  {
    id: "task-001",
    title: "Decorate the apartment & sublet",
    description: "Coordinate with decorator to prepare the apartment and sublet.",
    category: "General Prep",
    dueDate: "",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: true,
  },
  {
    id: "task-002",
    title: "Secure Mill Valley venue",
    description: "Book and confirm the Mill Valley venue for the wedding.",
    category: "General Prep",
    dueDate: "2026-02-02",
    status: "done",
    owner: "Saloni",
    fileIds: [],
    contextLog: ["Venue secured at Old Mill Park Amphitheatre"],
    decoratorTopic: false,
  },
  {
    id: "task-003",
    title: "Secure 3 hotel rooms",
    description: "Reserve 3 hotel rooms for out-of-town guests.",
    category: "General Prep",
    dueDate: "2026-02-12",
    status: "in-progress",
    owner: "Sahil",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-004",
    title: "Secure 1 sublet/airbnb for Rai/Mundhra fam",
    description: "Find and book a sublet or Airbnb for the Rai/Mundhra family.",
    category: "General Prep",
    dueDate: "2026-02-27",
    status: "in-progress",
    owner: "Sahil",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-005",
    title: "STD Invites",
    description: "Design and send out Save the Date invitations.",
    category: "General Prep",
    dueDate: "2026-02-12",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-006",
    title: "Wedding invites",
    description: "Design, print, and mail formal wedding invitations.",
    category: "General Prep",
    dueDate: "2026-02-27",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-007",
    title: "Figure out marriage license",
    description: "Research requirements and obtain marriage license.",
    category: "General Prep",
    dueDate: "2026-04-01",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },

  // ── Haldi ──────────────────────────────────────────────────────────────────
  {
    id: "task-008",
    title: "Procure haldi",
    description: "Source and purchase haldi (turmeric) for the ceremony.",
    category: "Haldi",
    dueDate: "2026-04-03",
    status: "todo",
    owner: "Sahil",
    fileIds: [],
    contextLog: [],
    decoratorTopic: true,
  },
  {
    id: "task-009",
    title: "Procure bowls",
    description: "Get decorative bowls for the haldi ceremony.",
    category: "Haldi",
    dueDate: "2026-04-03",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: true,
  },
  {
    id: "task-010",
    title: "Clothes for Saloni",
    description: "Select and purchase Saloni's outfit for the haldi ceremony.",
    category: "Haldi",
    dueDate: "2026-03-15",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-011",
    title: "Clothes for Sahil",
    description: "Select and purchase Sahil's outfit for the haldi ceremony.",
    category: "Haldi",
    dueDate: "2026-03-15",
    status: "todo",
    owner: "Sahil",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-012",
    title: "Haldi decoration",
    description: "Plan and arrange decorations for the haldi ceremony.",
    category: "Haldi",
    dueDate: "",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: true,
  },
  {
    id: "task-013",
    title: "Make playlist for haldi event",
    description: "Curate a fun playlist for the haldi ceremony.",
    category: "Haldi",
    dueDate: "2026-04-03",
    status: "todo",
    owner: "Unassigned",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },

  // ── Mehendi ────────────────────────────────────────────────────────────────
  {
    id: "task-014",
    title: "Book mehendi artist",
    description: "Find and book a mehendi artist for the ceremony.",
    category: "Mehendi",
    dueDate: "2026-02-18",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-015",
    title: "Decide mehendi pattern",
    description: "Choose mehendi designs and patterns for bridal and family.",
    category: "Mehendi",
    dueDate: "2026-04-03",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-016",
    title: "Finalize mehendi getters",
    description: "Confirm the guest list for the mehendi ceremony.",
    category: "Mehendi",
    dueDate: "2026-03-20",
    status: "todo",
    owner: "Sahil",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },

  // ── Ganesh Pooja + Wedding ─────────────────────────────────────────────────
  {
    id: "task-017",
    title: "Cute welcome poster (design)",
    description: "Design a welcome poster for guests at the venue.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "2026-03-06",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: true,
  },
  {
    id: "task-018",
    title: "Print poster + order easel",
    description: "Print the welcome poster and order an easel to display it.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "2026-03-20",
    status: "todo",
    owner: "Sahil",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-019",
    title: "Finalize decorator",
    description: "Confirm and finalize the event decorator.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "2026-02-10",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: true,
  },
  {
    id: "task-020",
    title: "Finalize decorations",
    description: "Finalize all decoration details with the decorator.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: true,
  },
  {
    id: "task-021",
    title: "Chairs",
    description: "Arrange chairs for the ceremony and reception.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: true,
  },
  {
    id: "task-022",
    title: "Music - live or speaker?",
    description: "Decide between live music or a speaker setup for the event.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "2026-02-20",
    status: "todo",
    owner: "Sahil",
    fileIds: [],
    contextLog: [],
    decoratorTopic: true,
  },
  {
    id: "task-023",
    title: "Pundit",
    description: "Find and book a pundit for the Ganesh Pooja and wedding ceremony.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "2026-02-20",
    status: "todo",
    owner: "Both",
    fileIds: [],
    contextLog: [],
    decoratorTopic: true,
  },
  {
    id: "task-024",
    title: "Saloni outfit",
    description: "Select and purchase Saloni's wedding outfit.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "2026-04-03",
    status: "in-progress",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-025",
    title: "Saloni jewelry",
    description: "Select and purchase jewelry for Saloni.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "2026-04-03",
    status: "in-progress",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-026",
    title: "Sahil outfit",
    description: "Select and purchase Sahil's wedding outfit.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "2026-04-03",
    status: "in-progress",
    owner: "Sahil",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-027",
    title: "Saloni mangalsutra",
    description: "Purchase the mangalsutra for the wedding ceremony.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "",
    status: "todo",
    owner: "Sahil",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-028",
    title: "Transportation from SF to Mill Valley",
    description: "Arrange transportation for guests from San Francisco to Mill Valley.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "2026-04-03",
    status: "todo",
    owner: "Sahil",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-029",
    title: "Refreshments",
    description: "Plan and order refreshments for guests.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "2026-04-03",
    status: "todo",
    owner: "Sahil",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-030",
    title: "Table for refreshments (water / snacks)",
    description: "Set up a refreshment table with water and snacks.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: true,
  },
  {
    id: "task-031",
    title: "Day of Planner - do we want? Quote checking",
    description: "Decide if a day-of coordinator is needed and get quotes.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "2026-02-25",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-032",
    title: "Trial - hair & make up (bridal)",
    description: "Schedule bridal hair and makeup trial session.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "2026-02-20",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-033",
    title: "Hair & makeup (bridal)",
    description: "Book bridal hair and makeup for the wedding day.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "2026-02-27",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-034",
    title: "Hair & makeup (family)",
    description: "Arrange hair and makeup services for family members.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "2026-02-27",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-035",
    title: "Pagdi (TBD)",
    description: "Decide on pagdi details — to be determined.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "",
    status: "todo",
    owner: "Unassigned",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-036",
    title: "Decide on photographer / videographer",
    description: "Research, interview, and book a photographer and videographer.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "2026-02-11",
    status: "todo",
    owner: "Sahil",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-037",
    title: "Wedding bands (Saloni)",
    description: "Select and purchase Saloni's wedding band.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "2026-02-27",
    status: "todo",
    owner: "Saloni",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-038",
    title: "Wedding bands (Sahil)",
    description: "Select and purchase Sahil's wedding band.",
    category: "Ganesh Pooja + Wedding",
    dueDate: "2026-02-27",
    status: "todo",
    owner: "Sahil",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },

  // ── Dinner / Hang ──────────────────────────────────────────────────────────
  {
    id: "task-039",
    title: "Reserve place & decoration",
    description: "Book a venue and plan decorations for the dinner/hang event.",
    category: "Dinner / Hang",
    dueDate: "2026-02-27",
    status: "todo",
    owner: "Sahil",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-040",
    title: "Decide on speakers / speeches",
    description: "Decide who will give speeches at the dinner.",
    category: "Dinner / Hang",
    dueDate: "2026-03-20",
    status: "todo",
    owner: "Both",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
  {
    id: "task-041",
    title: "Think about cute things we want there",
    description: "Brainstorm fun and personal touches for the dinner event.",
    category: "Dinner / Hang",
    dueDate: "2026-03-20",
    status: "todo",
    owner: "Both",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },

  // ── Night ──────────────────────────────────────────────────────────────────
  {
    id: "task-042",
    title: "Where are SaSa suhagrathing?",
    description: "Decide on the location for the wedding night.",
    category: "Night",
    dueDate: "2026-02-10",
    status: "todo",
    owner: "Sahil",
    fileIds: [],
    contextLog: [],
    decoratorTopic: false,
  },
];

// ─── Calendar events derived from tasks with due dates + wedding day ─────────

export const mockCalendarEvents: CalendarEvent[] = [
  // February deadlines
  {
    id: "evt-002",
    title: "Secure Mill Valley venue",
    date: "2026-02-02",
    type: "deadline",
    taskId: "task-002",
  },
  {
    id: "evt-042",
    title: "Where are SaSa suhagrathing?",
    date: "2026-02-10",
    type: "deadline",
    taskId: "task-042",
  },
  {
    id: "evt-019",
    title: "Finalize decorator",
    date: "2026-02-10",
    type: "deadline",
    taskId: "task-019",
  },
  {
    id: "evt-036",
    title: "Decide on photographer / videographer",
    date: "2026-02-11",
    type: "deadline",
    taskId: "task-036",
  },
  {
    id: "evt-003",
    title: "Secure 3 hotel rooms",
    date: "2026-02-12",
    type: "deadline",
    taskId: "task-003",
  },
  {
    id: "evt-005",
    title: "STD Invites",
    date: "2026-02-12",
    type: "deadline",
    taskId: "task-005",
  },
  {
    id: "evt-014",
    title: "Book mehendi artist",
    date: "2026-02-18",
    type: "deadline",
    taskId: "task-014",
  },
  {
    id: "evt-022",
    title: "Music - live or speaker?",
    date: "2026-02-20",
    type: "deadline",
    taskId: "task-022",
  },
  {
    id: "evt-023",
    title: "Pundit",
    date: "2026-02-20",
    type: "deadline",
    taskId: "task-023",
  },
  {
    id: "evt-032",
    title: "Trial - hair & makeup (bridal)",
    date: "2026-02-20",
    type: "appointment",
    taskId: "task-032",
  },
  {
    id: "evt-031",
    title: "Day of Planner quote checking",
    date: "2026-02-25",
    type: "deadline",
    taskId: "task-031",
  },
  {
    id: "evt-004",
    title: "Secure sublet/airbnb for family",
    date: "2026-02-27",
    type: "deadline",
    taskId: "task-004",
  },
  {
    id: "evt-006",
    title: "Wedding invites",
    date: "2026-02-27",
    type: "deadline",
    taskId: "task-006",
  },
  {
    id: "evt-033",
    title: "Hair & makeup (bridal)",
    date: "2026-02-27",
    type: "deadline",
    taskId: "task-033",
  },
  {
    id: "evt-034",
    title: "Hair & makeup (family)",
    date: "2026-02-27",
    type: "deadline",
    taskId: "task-034",
  },
  {
    id: "evt-037",
    title: "Wedding bands",
    date: "2026-02-27",
    type: "deadline",
    taskId: "task-037",
  },
  {
    id: "evt-039",
    title: "Reserve dinner place & decoration",
    date: "2026-02-27",
    type: "deadline",
    taskId: "task-039",
  },
  // March deadlines
  {
    id: "evt-017",
    title: "Cute welcome poster (design)",
    date: "2026-03-06",
    type: "deadline",
    taskId: "task-017",
  },
  {
    id: "evt-010",
    title: "Haldi clothes for Saloni",
    date: "2026-03-15",
    type: "deadline",
    taskId: "task-010",
  },
  {
    id: "evt-011",
    title: "Haldi clothes for Sahil",
    date: "2026-03-15",
    type: "deadline",
    taskId: "task-011",
  },
  {
    id: "evt-016",
    title: "Finalize mehendi getters",
    date: "2026-03-20",
    type: "deadline",
    taskId: "task-016",
  },
  {
    id: "evt-018",
    title: "Print poster + order easel",
    date: "2026-03-20",
    type: "deadline",
    taskId: "task-018",
  },
  {
    id: "evt-040",
    title: "Decide on speakers / speeches",
    date: "2026-03-20",
    type: "deadline",
    taskId: "task-040",
  },
  // April deadlines
  {
    id: "evt-007",
    title: "Figure out marriage license",
    date: "2026-04-01",
    type: "deadline",
    taskId: "task-007",
  },
  {
    id: "evt-008",
    title: "Procure haldi",
    date: "2026-04-03",
    type: "deadline",
    taskId: "task-008",
  },
  {
    id: "evt-024",
    title: "Saloni outfit due",
    date: "2026-04-03",
    type: "deadline",
    taskId: "task-024",
  },
  {
    id: "evt-026",
    title: "Sahil outfit due",
    date: "2026-04-03",
    type: "deadline",
    taskId: "task-026",
  },
  {
    id: "evt-028",
    title: "Transportation from SF to Mill Valley",
    date: "2026-04-03",
    type: "deadline",
    taskId: "task-028",
  },
  // Wedding day
  {
    id: "evt-wedding",
    title: "Wedding Day!",
    date: "2026-04-26",
    type: "milestone",
  },
];

// ─── Mock Drive files (unchanged — to be replaced with real Drive API) ───────

export const mockDriveFiles: DriveFile[] = [
  {
    id: "drive-001",
    name: "Photographer_Quotes.pdf",
    mimeType: "application/pdf",
    modifiedTime: "2025-12-20T14:30:00Z",
    size: "2.4 MB",
    iconLink: "",
    webViewLink: "#",
  },
  {
    id: "drive-002",
    name: "Guest_List_v3.xlsx",
    mimeType:
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    modifiedTime: "2026-01-10T09:15:00Z",
    size: "156 KB",
    iconLink: "",
    webViewLink: "#",
  },
  {
    id: "drive-003",
    name: "Venue_Floor_Plan.pdf",
    mimeType: "application/pdf",
    modifiedTime: "2025-11-05T16:45:00Z",
    size: "5.1 MB",
    iconLink: "",
    webViewLink: "#",
  },
  {
    id: "drive-004",
    name: "Catering_Menu_Options.docx",
    mimeType:
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    modifiedTime: "2026-01-08T11:20:00Z",
    size: "890 KB",
    iconLink: "",
    webViewLink: "#",
  },
  {
    id: "drive-005",
    name: "Floral_Inspiration_Board.jpg",
    mimeType: "image/jpeg",
    modifiedTime: "2026-01-12T08:00:00Z",
    size: "3.7 MB",
    iconLink: "",
    webViewLink: "#",
  },
  {
    id: "drive-006",
    name: "Budget_Tracker.xlsx",
    mimeType:
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    modifiedTime: "2026-01-14T17:30:00Z",
    size: "210 KB",
    iconLink: "",
    webViewLink: "#",
  },
  {
    id: "drive-007",
    name: "Invitation_Design_Draft.png",
    mimeType: "image/png",
    modifiedTime: "2026-01-05T13:10:00Z",
    size: "1.2 MB",
    iconLink: "",
    webViewLink: "#",
  },
  {
    id: "drive-008",
    name: "Seating_Chart_Draft.pdf",
    mimeType: "application/pdf",
    modifiedTime: "2026-01-09T10:45:00Z",
    size: "420 KB",
    iconLink: "",
    webViewLink: "#",
  },
];

export const mockChatMessages: {
  role: "user" | "assistant";
  content: string;
}[] = [
  {
    role: "user",
    content: "What's our wedding date?",
  },
  {
    role: "assistant",
    content:
      "Your wedding is on **April 26, 2026** at **Old Mill Park Amphitheatre** in Mill Valley. Based on your task list, you have 42 items to track across Haldi, Mehendi, Ganesh Pooja + Wedding, Dinner, and more!",
  },
];
